name: Arduino Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    name: ${{ matrix.script.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script:
          - name: temperature_logger_lm_35_factory_test
            command: arduino-cli compile --fqbn arduino:avr:uno temperature_logger_lm_35_factory_test
#          - name: some_other_script
#            command: ./scripts/some_script.sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install arduino-cli
        uses: arduino/setup-arduino-cli@v2
        with:
          version: '1.x'

      - name: Update index and install AVR core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Run script
        run: |
          echo "Running: ${{ matrix.script.command }}"
          ${{ matrix.script.command }}
